//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUyg3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblogretmen
    {
        public int ogretmenid { get; set; }
        public string ogretmenad { get; set; }
        public string ogretmensoyad { get; set; }
        public string ogretmenders { get; set; }
    
        public virtual tblsinif tblsinif { get; set; }
    }
}
