//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUyg3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblogrenci
    {
        public int ogrenciid { get; set; }
        public string ogrenciad { get; set; }
        public string ogrencisoyad { get; set; }
        public string ogrencisinif { get; set; }
        public string ogrencitel { get; set; }
    }
}
