//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSistem1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOgretmen
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> Brans1 { get; set; }
        public Nullable<int> Brans2 { get; set; }
    
        public virtual tbSinif tbSinif { get; set; }
        public virtual tbSinif tbSinif1 { get; set; }
    }
}
