//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSistem1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOgrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOgrenci()
        {
            this.tbListe = new HashSet<tbListe>();
        }
    
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbListe> tbListe { get; set; }
    }
}
